name = "snape"
# Redeploy trigger — CF Pages picks up env secrets on new builds.
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "snape-db"
database_id = "9901bd47-921b-4167-ac66-94a24e909958"
migrations_dir = "db/migrations"
